
// This file is now a pure data file with no React/JSX dependencies.
// It can be safely imported by both server and client components.

import type { ReactNode } from 'react';

export type Field = {
  id: string;
  name: string;
  type: 'text' | 'file' | 'textarea' | 'select' | 'button' | 'number' | 'group-header';
  placeholder?: string;
  description: string;
  options?: string[];
  multiple?: boolean;
  cta?: string;
  value?: string;
  hidden?: boolean;
};

export type FilterCategory = 'All' | 'Lead Gen' | 'Creative' | 'Sales Tools' | 'Social & Comms' | 'Web' | 'Editing' | 'Ads' | 'Marketing' | 'Market Library' | 'Utilities' | 'Listing Intelligence AI' | 'TikTok AI Suite' | 'Google AI Suite' | 'Video' | 'Archy' | 'Meta Pilot' | 'Market Intelligence' | 'Listing & CRM' | 'Developer & Backend' | 'EBRAM';

export type Feature = {
  id: string;
  title: string;
  dashboardTitle?: string;
  description: string;
  icon: string; // Changed from React.ElementType to string
  color: string;
  cta: string;
  categories: FilterCategory[];
  mindMapCategory: 'Archy' | 'Meta Pilot' | 'Market Intelligence' | 'Listing & CRM' | 'Developer & Backend' | 'Internal' | 'EBRAM';
  badge?: 'NEW' | 'BETA' | 'SOON' | 'Pilot*';
  isPage?: boolean;
  href: string;
  guideHref?: string;
  details: {
    steps: { text: string; icon: string }[]; // Changed icon to string
    aiVsManual: {
      metric: string;
      manual: string;
      ai: string;
      icon: string; // Changed icon to string
    }[];
    synergy: { tool: string; benefit: string }[];
    faqs: { question: string; answer: string }[];
  };
  creationFields: Field[];
  renderResult?: (result: any, toast: any) => ReactNode;
};

export const tools: Omit<Feature, 'renderResult'>[] = [
  // Archy (Creative Marketing)
  {
    id: 'ai-video-presenter',
    title: 'AI Video Presenter',
    description: 'Create a lifelike AI presenter to deliver your project pitch.',
    icon: 'User',
    color: '#f43f5e',
    cta: 'Generate Video',
    categories: ['Creative', 'Video', 'Marketing', 'Ads', 'Archy'],
    mindMapCategory: 'Archy',
    isPage: true,
    badge: 'NEW',
    href: '/dashboard/tool/ai-video-presenter',
    guideHref: '/blog/ai-video-presenter',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'aerial-view-generator',
    title: 'Aerial View Generator',
    description: 'Create cinematic drone tours of any property from an address.',
    icon: 'Film',
    color: '#d946ef',
    cta: 'Generate View',
    categories: ['Creative', 'Video', 'Marketing', 'Ads', 'Archy'],
    mindMapCategory: 'Archy',
    isPage: true,
    badge: 'NEW',
    href: '/dashboard/tool/aerial-view-generator',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'ugc-script-writer',
    title: 'UGC Script Writer',
    description: 'Generate authentic, user-generated content style video ad scripts.',
    icon: 'PenSquare',
    color: '#8b5cf6',
    cta: 'Generate Script',
    categories: ['Creative', 'Ads', 'Social & Comms', 'Archy'],
    mindMapCategory: 'Archy',
    isPage: true,
    badge: 'NEW',
    href: '/dashboard/tool/ugc-script-writer',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'youtube-video-editor',
    title: 'AI YouTube Video Editor',
    description: 'Edit any video to be YouTube-ready.',
    icon: 'Youtube',
    color: '#ef4444', 
    cta: 'Edit YouTube Video',
    categories: ['Creative', 'Editing', 'Social & Comms', 'Archy'],
    mindMapCategory: 'Archy',
    badge: 'NEW',
    isPage: true,
    href: '/dashboard/tool/youtube-video-editor',
    guideHref: '/blog/youtube-video-editor',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'landing-pages',
    title: 'Landing Page Builder',
    description: 'Launch a high-converting page in minutes.',
    icon: 'LayoutTemplate',
    color: '#22c55e', 
    cta: 'Create Landing Page',
    categories: ['Creative', 'Web', 'Archy'],
    mindMapCategory: 'Archy',
    isPage: true,
    href: '/dashboard/tool/landing-pages',
    guideHref: '/blog/landing-pages',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'rebranding',
    title: 'Automated Rebranding',
    description: 'Apply your brand identity to any brochure.',
    icon: 'Palette',
    color: '#f97316', 
    cta: 'Rebrand a Document',
    categories: ['Creative', 'Editing', 'Archy'],
    mindMapCategory: 'Archy',
    badge: 'NEW',
    isPage: true,
    href: '/dashboard/tool/rebranding',
    guideHref: '/blog/rebranding',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'brochure-translator',
    title: 'Brochure Translator',
    description: 'Translate any brochure to multiple languages in seconds.',
    icon: 'Languages',
    color: '#8b5cf6', 
    cta: 'Translate Brochure',
    categories: ['Creative', 'Editing', 'Sales Tools', 'Archy'],
    mindMapCategory: 'Archy',
    href: '/dashboard/tool/brochure-translator',
    guideHref: '/blog/brochure-translator',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [
      { id: 'brochureDataUri', name: 'Source Brochure', type: 'file', description: 'Upload the PDF brochure you want to translate.' },
      { id: 'targetLanguage', name: 'Target Language', type: 'select', options: ['Arabic', 'English', 'Chinese', 'Russian', 'French', 'Italian', 'Spanish', 'Japanese'], placeholder: 'Select a language', description: 'Choose the language to translate into.' },
    ],
  },

  // Meta Pilot (Campaign Automation)
  {
    id: 'meta-auto-pilot',
    title: 'Meta Auto Pilot',
    description: 'The execution terminal for your Meta Ads campaigns.',
    icon: 'Star',
    color: '#fbbf24', 
    cta: 'Run Workflow',
    categories: ['Marketing', 'Ads', 'Lead Gen', 'Meta Pilot'],
    mindMapCategory: 'Meta Pilot',
    badge: 'Pilot*',
    isPage: true,
    href: '/dashboard/tool/meta-auto-pilot',
    guideHref: '/blog/meta-auto-pilot',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'meta-ads-copilot',
    title: 'Meta Ads Co-Pilot',
    dashboardTitle: 'Campaign Builder',
    description: 'Your dedicated agent for Facebook & Instagram advertising.',
    icon: 'Facebook',
    color: '#1d4ed8', 
    cta: 'Create Campaign',
    categories: ['Marketing', 'Ads', 'Lead Gen', 'Meta Pilot'],
    mindMapCategory: 'Meta Pilot',
    badge: 'NEW',
    isPage: true,
    href: '/dashboard/tool/meta-ads-copilot',
    guideHref: '/blog/meta-ads-copilot',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'audience-creator',
    title: 'Audience Creator',
    description: 'Find high-intent buyers before they search.',
    icon: 'Binoculars',
    color: '#3b82f6', 
    cta: 'Generate Strategies',
    categories: ['Marketing', 'Lead Gen', 'Ads', 'Meta Pilot'],
    mindMapCategory: 'Meta Pilot',
    badge: 'NEW',
    isPage: true,
    href: '/dashboard/tool/audience-creator',
    guideHref: '/blog/audience-creator',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [
       { id: 'projectId', name: 'Project', type: 'select', options: ['Emaar Beachfront', 'Damac Hills 2', 'Sobha Hartland', 'Add New Project...'], placeholder: 'Select a project', description: 'Choose the project you want to create an audience for.' },
    ],
  },
  {
    id: 'insta-ads-designer',
    title: 'Insta Ads Designer',
    description: 'Create perfect ads for Instagram Stories & Feed.',
    icon: 'Instagram',
    color: '#ec4899', 
    cta: 'Generate Ad',
    categories: ['Ads', 'Creative', 'Social & Comms', 'Meta Pilot'],
    mindMapCategory: 'Meta Pilot',
    isPage: false,
    href: '/dashboard/tool/insta-ads-designer',
    guideHref: '/blog/insta-ads-designer',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [
      { id: 'projectId', name: 'Project', type: 'select', options: ['Emaar Beachfront', 'Damac Hills 2', 'Sobha Hartland', 'Add New Project...'], placeholder: 'Select a project', description: 'Choose from your saved projects.' },
      { id: 'brochureDataUri', name: 'Or Upload Developer Brochure', type: 'file', description: 'Upload the original PDF for more detailed ad generation.' },
      { id: 'focusArea', name: 'Ad Focus', type: 'select', options: ['Luxury & Prestige', 'Family-Friendly', 'Investment Opportunity', 'Modern & Urban', 'First-Time Buyer'], placeholder: 'Select the ad\'s main angle', description: 'What key aspect should the ad highlight?' },
      { id: 'toneOfVoice', name: 'Tone of Voice', type: 'select', options: ['Professional', 'Exciting', 'Welcoming', 'Urgent', 'Sophisticated'], placeholder: 'Select a tone', description: 'Set the tone for the ad copy.' },
      { id: 'additionalInformation', name: 'Additional Information', type: 'textarea', placeholder: 'e.g., "Limited time offer: 2 years of service charges waived."', description: 'Add any other key details or offers. (Optional)' },
    ],
  },
  {
    id: 'instagram-content-creator',
    title: 'Social Content Creator',
    description: 'Generate a 7-day social content plan from a single topic.',
    icon: 'Share2',
    color: '#ea580c',
    cta: 'Generate Content Strategy',
    categories: ['Marketing', 'Creative', 'Social & Comms', 'Meta Pilot'],
    mindMapCategory: 'Meta Pilot',
    isPage: false,
    href: '/dashboard/tool/instagram-content-creator',
    guideHref: '/blog/instagram-content-creator',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [
        { id: 'dataStore', name: 'Data Store', type: 'select', options: ['None (General Knowledge)', 'MarketMedia-Lib', 'SuperSeller', 'Watcher'], placeholder: 'Select a data store', description: 'The knowledge base the AI will use to write content.' },
        { id: 'topic', name: 'Topic or Theme', type: 'text', placeholder: 'e.g., "The benefits of living in Dubai Marina"', description: 'The core idea for your content plan.' },
        { id: 'platform', name: 'Platform', type: 'select', options: ['Instagram', 'Facebook', 'LinkedIn', 'Twitter'], placeholder: 'Select a platform', description: 'The platform you are creating content for.' },
        { id: 'tone', name: 'Tone of Voice', type: 'select', options: ['Professional', 'Friendly', 'Humorous', 'Authoritative'], placeholder: 'Select a tone', description: 'Set the tone for the generated posts.' },
    ],
  },

  // Market Intelligence Tools
  {
    id: 'keyword-planner',
    title: 'AI Keyword Planner',
    description: 'Generate strategic keyword plans for Google Ads campaigns.',
    icon: 'Wand2',
    color: '#eab308',
    cta: 'Generate Plan',
    categories: ['Market Intelligence', 'Ads'],
    mindMapCategory: 'Market Intelligence',
    isPage: true,
    badge: 'NEW',
    href: '/dashboard/tool/keyword-planner',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'market-reports',
    title: 'AI Market Reports',
    description: 'Generate on-demand, data-rich market reports for any location.',
    icon: 'LineChart',
    color: '#f59e0b',
    cta: 'Generate Report',
    categories: ['Market Library', 'Sales Tools', 'Market Intelligence'],
    mindMapCategory: 'Market Intelligence',
    isPage: true,
    href: '/dashboard/tool/market-reports',
    guideHref: '/blog/market-reports',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'price-estimator',
    title: 'AI Price Estimator',
    description: 'Get an AI-powered price estimate for any property.',
    icon: 'Wallet',
    color: '#16a34a',
    cta: 'Estimate Price',
    categories: ['Sales Tools', 'Utilities', 'Market Intelligence'],
    mindMapCategory: 'Market Intelligence',
    isPage: true,
    badge: 'NEW',
    href: '/dashboard/tool/price-estimator',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'market-trends',
    title: 'Market Trends Watcher',
    description: 'Identify emerging market trends before they become mainstream.',
    icon: 'TrendingUp',
    color: '#14b8a6', 
    cta: 'Analyze Trends',
    categories: ['Market Library', 'Sales Tools', 'Lead Gen', 'Market Intelligence'],
    mindMapCategory: 'Market Intelligence',
    isPage: true,
    href: '/dashboard/tool/market-trends',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
    {
    id: 'investor-matching',
    title: 'Investor Matching',
    description: 'Pair investment properties with the right clients from your database.',
    icon: 'Users2',
    color: '#6366f1', 
    cta: 'Generate Investor Match',
    categories: ['Sales Tools', 'Lead Gen', 'Market Intelligence'],
    mindMapCategory: 'Market Intelligence',
    badge: 'SOON',
    href: '/dashboard/tool/investor-matching',
    guideHref: '/blog/investor-matching',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [
      { id: 'clientDatabase', name: 'Your Client List', type: 'file', description: 'Upload a CSV of your investor contacts for the AI to analyze.' },
      { id: 'propertyType', name: 'Property Type', type: 'select', options: ["Duplex", "Triplex", "Fourplex", "Multi-Family (5+ units)", "Commercial Retail", "Office Space"], placeholder: 'Select property type', description: 'Type of investment property.' },
      { id: 'location', name: 'Location', type: 'text', placeholder: 'e.g., Dubai Marina, Dubai', description: 'City and state of the property.'},
      { id: 'price', name: 'Price', type: 'number', placeholder: 'e.g., 2500000', description: 'Asking price in the local currency.'},
      { id: 'capRate', name: 'Cap Rate (%)', type: 'number', placeholder: 'e.g., 6.5', description: 'The capitalization rate of the property.'},
      { id: 'investmentThesis', name: 'Investment Thesis', type: 'select', options: ["Value-Add / Renovation", "Turnkey Rental", "Long-Term Appreciation", "Development Opportunity", "1031 Exchange"], placeholder: 'Select investment strategy', description: 'Primary strategy for this investment.'},
      { id: 'keyFeatures', name: 'Key Features', type: 'textarea', placeholder: 'e.g., Long-term tenants in place, zoned for mixed-use, located in an opportunity zone.', description: 'Additional selling points for an investor.' },
    ],
  },
    {
    id: 'offer-generator',
    title: 'Multi-Offer Builder',
    description: 'Create side-by-side property comparisons for clients.',
    icon: 'Briefcase',
    color: '#78716c', 
    cta: 'Create Offer Package',
    categories: ['Sales Tools', 'Editing', 'Market Intelligence'],
    mindMapCategory: 'Market Intelligence',
    badge: 'SOON',
    href: '/dashboard/tool/offer-generator',
    guideHref: '/blog/email-creator',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [
      { id: 'properties', name: 'Properties', type: 'textarea', placeholder: 'List property addresses, one per line', description: 'The properties to include in the offer package.' },
      { id: 'clientInfo', name: 'Client Info', type: 'text', placeholder: 'e.g., John Smith, Budget: AED 5.5M', description: 'Basic information about the client.' },
      { id: 'terms', name: 'Offer Terms', type: 'textarea', placeholder: 'e.g., 20% down, 30-day closing, inspection contingency', description: 'Key terms to include in the offers.' },
    ],
  },
  
  // Listing & CRM Tools
  {
    id: 'lead-to-deal-pipeline',
    title: 'Lead-to-Deal Pipeline',
    description: 'An automated workflow that investigates, evaluates, and matches leads.',
    icon: 'Bot',
    color: '#f59e0b',
    cta: 'Start Pipeline',
    categories: ['Sales Tools', 'Lead Gen', 'Listing & CRM'],
    mindMapCategory: 'Listing & CRM',
    badge: 'Pilot*',
    isPage: true,
    href: '/dashboard/tool/lead-to-deal-pipeline',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'listing-manager',
    title: 'Listing Manager',
    description: 'Your central hub to prepare and syndicate listings to major portals.',
    icon: 'Building',
    color: '#0891b2',
    cta: 'Manage Listings',
    categories: ['Listing & CRM', 'Sales Tools', 'Web'],
    mindMapCategory: 'Listing & CRM',
    isPage: true,
    badge: 'NEW',
    href: '/dashboard/tool/listing-manager',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'listing-performance',
    title: 'Listing Performance',
    description: 'Track listing views, visitor analytics, and lead generation.',
    icon: 'BarChart',
    color: '#ef4444',
    cta: 'View Performance',
    categories: ['Listing & CRM', 'Sales Tools', 'Ads'],
    mindMapCategory: 'Listing & CRM',
    isPage: true,
    badge: 'NEW',
    href: '/dashboard/tool/listing-performance',
    guideHref: '/blog/listing-performance',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'listing-generator',
    title: 'Listing Generator',
    description: 'Craft perfect listings for portals like Property Finder & Bayut.',
    icon: 'PenTool',
    color: '#10b981',
    cta: 'Create Listing',
    categories: ['Listing & CRM', 'Sales Tools', 'Editing'],
    mindMapCategory: 'Listing & CRM',
    badge: 'SOON',
    href: '/dashboard/tool/listing-generator',
    guideHref: '/blog/bayut-listing-ai',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [
      { id: 'platform', name: 'Platform', type: 'select', options: ['Property Finder', 'Bayut', 'Dubizzle', 'Generic'], placeholder: 'Select a listing platform', description: 'The listing portal you are writing for.' },
      { id: 'propertyAddress', name: 'Property Address', type: 'text', placeholder: 'e.g., Villa 1, The Lakes, Dubai', description: 'The address of the a property.' },
      { id: 'keyDetails', name: 'Key Details', type: 'text', placeholder: 'e.g., 5 beds, 6 baths, 4,500 sqft', description: 'Provide the basic stats.' },
      { id: 'uniqueFeatures', name: 'Unique Features', type: 'textarea', placeholder: 'e.g., Upgraded interior, private pool, lake view', description: 'What makes this property special?' },
      { id: 'tone', name: 'Tone', type: 'select', options: ['Luxury', 'Family-Friendly', 'Modern', 'Cozy', 'Urgent'], placeholder: 'Select a tone', description: 'The tone of voice for the listing.' },
    ],
  },
  {
    id: 'payment-planner',
    title: 'AI Payment Planner',
    description: 'Generate clear, client-friendly payment plans for any property.',
    icon: 'Percent',
    color: '#22c55e', 
    cta: 'Create Plan',
    categories: ['Sales Tools', 'Utilities', 'Listing & CRM'],
    mindMapCategory: 'Listing & CRM',
    isPage: true,
    href: '/dashboard/tool/payment-planner',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'whatsapp-campaigns',
    title: 'WhatsApp Manager',
    description: 'Send personalized broadcasts and drip campaigns.',
    icon: 'Phone',
    color: '#16a34a', 
    cta: 'Send WhatsApp Campaign',
    categories: ['Sales Tools', 'Social & Comms', 'Lead Gen', 'Listing & CRM'],
    mindMapCategory: 'Listing & CRM',
    badge: 'SOON',
    href: '/dashboard/tool/whatsapp-campaigns',
    guideHref: '/blog/instagram-admin-ai',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [
      { id: 'contacts', name: 'Contact List', type: 'file', description: 'Upload a CSV with names and numbers.' },
      { id: 'campaignType', name: 'Campaign Type', type: 'select', options: ["New Listing Announcement", "Open House Invitation", "Price Reduction Alert", "Post-Viewing Follow-up"], placeholder: 'Select a message template', description: 'Choose the goal of your campaign.' },
      { id: 'sendTime', name: 'Schedule', type: 'select', options: ['Send Immediately', 'Schedule for 1 hour from now', 'Schedule for tomorrow at 9 AM'], placeholder: 'Select send time', description: 'When should the campaign be sent?' },
    ],
  },
  {
    id: 'lead-investigator',
    title: 'Lead Investigator AI',
    description: 'Find social profiles and professional history for any lead.',
    icon: 'Search',
    color: '#0284c7',
    cta: 'Investigate Lead',
    categories: ['Sales Tools', 'Lead Gen', 'Listing & CRM'],
    mindMapCategory: 'Listing & CRM',
    isPage: true,
    href: '/dashboard/tool/lead-investigator',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [
      { id: 'name', name: 'Lead\'s Full Name', type: 'text', placeholder: 'e.g., John Smith', description: 'The full name of the person you are investigating.' },
      { id: 'company', name: 'Company (Optional)', type: 'text', placeholder: 'e.g., ACME Inc.', description: 'The company they work for, if known.' },
      { id: 'email', name: 'Email (Optional)', type: 'text', placeholder: 'e.g., john.smith@acme.com', description: 'Their email address, if known.' },
      { id: 'location', name: 'Location (Optional)', type: 'text', placeholder: 'e.g., Dubai, UAE', description: 'Their general location, if known.' },
      { id: 'role', name: 'Role (Optional)', type: 'text', placeholder: 'e.g., CEO, Founder, Head of Sales', description: 'Their job title, if known.' },
    ],
  },
  {
    id: 'crm-assistant',
    title: 'CRM Memory',
    description: 'Remembers every client interaction, preference, and detail.',
    icon: 'Database',
    color: '#0d9488', 
    cta: 'Get Client Record',
    categories: ['Sales Tools', 'Lead Gen', 'Listing & CRM'],
    mindMapCategory: 'Listing & CRM',
    badge: 'SOON',
    href: '/dashboard/tool/crm-assistant',
    guideHref: '/blog/ai-brand-creator',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [
      { id: 'clientName', name: 'Client Name', type: 'text', placeholder: 'e.g., "Jane Doe" or "the buyer for 123 Main St"', description: 'Ask about a specific client.' },
      { id: 'query', name: 'Your Question', type: 'textarea', placeholder: 'e.g., "Summarize my last call with her" or "Does she have kids?"', description: 'What do you need to know?' },
    ],
  },

  // Developer & Backend Tools
  {
    id: 'vm-creator',
    title: 'VM Creator',
    description: 'Provision Google Cloud virtual machines with an AI command.',
    icon: 'Server',
    color: '#4f46e5',
    cta: 'Create VM',
    categories: ['Utilities', 'Developer & Backend'],
    mindMapCategory: 'Developer & Backend',
    badge: 'NEW',
    isPage: false,
    href: '/dashboard/tool/vm-creator',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [
      { id: 'instanceName', name: 'Instance Name', type: 'text', placeholder: 'e.g., my-test-instance', description: 'The name for your new virtual machine.' },
      { id: 'zone', name: 'Zone', type: 'select', options: ['us-central1-a', 'us-central1-b', 'us-central1-c'], placeholder: 'Select a zone', description: 'The Google Cloud zone to create the VM in.' },
      { id: 'machineType', name: 'Machine Type', type: 'select', options: ['e2-micro', 'e2-small', 'e2-medium', 'n1-standard-1'], placeholder: 'Select a machine type', description: 'The size and power of the VM.' },
      { id: 'sourceImageFamily', name: 'Operating System', type: 'select', options: ['debian-12', 'debian-11', 'ubuntu-2204-lts', 'ubuntu-2004-lts'], placeholder: 'Select an OS', description: 'The operating system for the VM.' },
      { id: 'diskSizeGb', name: 'Disk Size (GB)', type: 'number', placeholder: '10', description: 'The size of the boot disk in gigabytes.' },
    ],
  },
  {
    id: 'property-finder-sync',
    title: 'Property Finder Pilot',
    description: 'PULL data from Property Finder, or PUSH listing plans to it.',
    icon: 'Server',
    color: '#6b7280',
    cta: 'Go to Pilot',
    categories: ['Utilities', 'Web', 'Listing & CRM', 'Developer & Backend'],
    mindMapCategory: 'Developer & Backend',
    isPage: true,
    badge: 'Pilot*',
    href: '/dashboard/tool/property-finder-sync',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'bayut-sync',
    title: 'Bayut Pilot',
    description: 'PULL data from Bayut, or PUSH listing plans to it.',
    icon: 'Server',
    color: '#6b7280',
    cta: 'Go to Pilot',
    categories: ['Utilities', 'Web', 'Listing & CRM', 'Developer & Backend'],
    mindMapCategory: 'Developer & Backend',
    isPage: true,
    badge: 'Pilot*',
    href: '/dashboard/tool/bayut-sync',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'creative-execution-terminal',
    title: 'Creative Execution Terminal',
    description: 'The execution engine for your creative tasks.',
    icon: 'Terminal',
    color: '#64748b', 
    cta: 'Go to Terminal',
    categories: ['Utilities', 'Developer & Backend'],
    mindMapCategory: 'Developer & Backend',
    isPage: true,
    badge: 'Pilot*',
    href: '/dashboard/tool/creative-execution-terminal',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
  {
    id: 'pdf-editor',
    title: 'Visual PDF Editor',
    description: 'Edit any PDF with simple visual tools and AI commands.',
    icon: 'Edit',
    color: '#dc2626',
    cta: 'Edit a PDF',
    categories: ['Editing', 'Creative', 'Developer & Backend'],
    mindMapCategory: 'Developer & Backend',
    badge: 'BETA',
    isPage: true,
    href: '/dashboard/tool/pdf-editor',
    guideHref: '/blog/pdf-editor',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [
      { id: 'sourcePdf', name: 'Source PDF', type: 'file', description: 'The PDF you want to edit.' },
      { id: 'newImages', name: 'New Images (optional)', type: 'file', multiple: true, description: 'Upload any new images you want to add or swap.' },
      { id: 'editInstructions', name: 'Editing Instructions', type: 'textarea', placeholder: 'e.g., "Replace the logo on page 1 with the new one I uploaded. Change the price on page 3 to AED 2.5M."', description: 'Tell the AI what changes to make.' },
    ],
  },
  // EBRAM (Legal Intelligence)
  {
    id: 'lease-reviewer',
    title: 'AI Lease Reviewer',
    description: 'Analyze lease agreements for risks and get plain-English summaries.',
    icon: 'ShieldCheck',
    color: '#4ade80',
    cta: 'Review Lease',
    categories: ['Sales Tools', 'Utilities', 'EBRAM'],
    mindMapCategory: 'EBRAM',
    isPage: true,
    badge: 'NEW',
    href: '/dashboard/tool/lease-reviewer',
    details: { steps: [], aiVsManual: [], synergy: [], faqs: [] },
    creationFields: [],
  },
];
